'use client'

import { useActionState, useEffect, useRef } from 'react'
import { useFormStatus } from 'react-dom'
import { onGenerate, type FormState } from '@/app/image-generator/actions'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useToast } from '@/hooks/use-toast'
import { Image as ImageIcon, Sparkles } from 'lucide-react'
import Image from 'next/image'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

const initialState: FormState = {
  message: '',
}

const games = [
    { slug: "astro-clash", title: "Astro Clash" },
    { slug: "build-n-bounce", title: "Build 'n' Bounce" },
    { slug: "kart-havoc", title: "Kart Havoc" },
    { slug: "soccer-scramble", title: "Soccer Scramble" },
    { slug: "goblin-gold-grab", title: "Goblin Gold Grab" },
]

function SubmitButton() {
  const { pending } = useFormStatus()
  return (
    <Button type="submit" disabled={pending} className="w-full">
      {pending ? (
        'Generating...'
      ) : (
        <>
          <Sparkles className="mr-2 h-4 w-4" /> Generate Image
        </>
      )}
    </Button>
  )
}

export default function ImageGeneratorForm() {
  const [state, formAction] = useActionState(onGenerate, initialState)
  const { toast } = useToast()
  const formRef = useRef<HTMLFormElement>(null)

  useEffect(() => {
    if (state.message && !state.data) {
      toast({
        title: 'Error',
        description: state.issues ? state.issues.join('\n') : state.message,
        variant: 'destructive',
      })
    }
    if (state.data?.imageUrl && state.data?.gameSlug) {
      toast({
        title: 'Success!',
        description: 'Your image has been generated below and updated on the home page.',
      })
      // Save to localStorage
      try {
        localStorage.setItem(`game-image-${state.data.gameSlug}`, state.data.imageUrl)
      } catch (e) {
        console.error("Failed to save image to localStorage", e)
        toast({
            title: 'Could not save image',
            description: 'Your browser may be out of space or in private mode.',
            variant: 'destructive',
        })
      }
    }
  }, [state, toast])

  return (
    <form ref={formRef} action={formAction} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="gameSlug">Game</Label>
        <Select name="gameSlug" defaultValue={state.fields?.gameSlug}>
          <SelectTrigger>
            <SelectValue placeholder="Select a game to generate an image for..." />
          </SelectTrigger>
          <SelectContent>
            {games.map(game => (
              <SelectItem key={game.slug} value={game.slug}>{game.title}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>
      <div className="space-y-2">
        <Label htmlFor="prompt">Image Prompt</Label>
        <Input
          id="prompt"
          name="prompt"
          placeholder="e.g., A heroic knight riding a giant snail, pixel art"
          defaultValue={state.fields?.prompt}
          required
        />
      </div>
      <SubmitButton />

      {state.data?.imageUrl && (
        <Card className="mt-6 bg-secondary animate-fade-in">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ImageIcon className="text-primary" />
              Generated Image
            </CardTitle>
            <CardDescription>
              Here is the image generated by the AI.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="relative aspect-square w-full overflow-hidden rounded-md border bg-background/50">
              <Image
                src={state.data.imageUrl}
                alt={state.fields?.prompt || "Generated image"}
                fill
                className="object-contain"
              />
            </div>
          </CardContent>
        </Card>
      )}
    </form>
  )
}
