'use client'

import { useActionState, useEffect, useRef } from 'react'
import { useFormStatus } from 'react-dom'
import { onGenerate, type FormState } from '@/app/image-generator/actions'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useToast } from '@/hooks/use-toast'
import { Image as ImageIcon, Sparkles } from 'lucide-react'
import Image from 'next/image'

const initialState: FormState = {
  message: '',
}

function SubmitButton() {
  const { pending } = useFormStatus()
  return (
    <Button type="submit" disabled={pending} className="w-full">
      {pending ? (
        'Generating...'
      ) : (
        <>
          <Sparkles className="mr-2 h-4 w-4" /> Generate Image
        </>
      )}
    </Button>
  )
}

export default function ImageGeneratorForm() {
  const [state, formAction] = useActionState(onGenerate, initialState)
  const { toast } = useToast()
  const formRef = useRef<HTMLFormElement>(null)

  useEffect(() => {
    if (state.message && !state.data) {
      toast({
        title: 'Error',
        description: state.issues ? state.issues.join('\n') : state.message,
        variant: 'destructive',
      })
    }
    if (state.data) {
      toast({
        title: 'Success!',
        description: 'Your image has been generated below.',
      })
    }
  }, [state, toast])

  return (
    <form ref={formRef} action={formAction} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="prompt">Image Prompt</Label>
        <Input
          id="prompt"
          name="prompt"
          placeholder="e.g., A heroic knight riding a giant snail, pixel art"
          defaultValue={state.fields?.prompt}
          required
        />
      </div>
      <SubmitButton />

      {state.data?.imageUrl && (
        <Card className="mt-6 bg-secondary animate-fade-in">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ImageIcon className="text-primary" />
              Generated Image
            </CardTitle>
            <CardDescription>
              Here is the image generated by the AI.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="relative aspect-square w-full overflow-hidden rounded-md border bg-background/50">
              <Image
                src={state.data.imageUrl}
                alt={state.fields?.prompt || "Generated image"}
                fill
                className="object-contain"
              />
            </div>
          </CardContent>
        </Card>
      )}
    </form>
  )
}
